# Boilerplate code generated by OVITO Pro 3.7.11
from ovito.io import *
from ovito.modifiers import *
from ovito.data import *
from ovito.pipeline import *
import sys

# Data import:
pipeline = import_file(sys.argv[1], multiple_frames = True)

#pipeline.modifiers.append(WrapPeriodicImagesModifier())

# Compute property:
pipeline.modifiers.append(ComputePropertyModifier(output_property = 'Displacement Magnitude'))

# Displacement vectors:
pipeline.modifiers.append(CalculateDisplacementsModifier(
    use_frame_offset = True, 
    frame_offset=-1,
    affine_mapping = ReferenceConfigurationModifier.AffineMapping.ToCurrent,
    minimum_image_convention=True))

# Expression selection:
pipeline.modifiers.append(ExpressionSelectionModifier(expression = 'ParticleType!=1'))

# Coordination analysis:
pipeline.modifiers.append(CoordinationAnalysisModifier(
    cutoff = 1.3, 
    number_of_bins = 100, 
    only_selected = True))
    
num_frames=pipeline.source.num_frames

for frame in range(1,pipeline.source.num_frames):
    data = pipeline.compute(frame)
    
export_file(pipeline, sys.argv[2], "xyz", columns =["Particle Identifier", "Particle Type", "Position.X", "Position.Y", "Position.Z", "Coordination","Displacement Magnitude"],start_frame=1,end_frame=num_frames-1,multiple_frames=True)
